import 'dart:convert';
import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import '../data/models/session_model.dart';

class DeicInfo {
  final String name;
  final String address;
  final String phone;

  const DeicInfo({
    required this.name,
    required this.address,
    required this.phone,
  });

  factory DeicInfo.fromJson(Map<String, dynamic> json) => DeicInfo(
    name: json['name'] as String,
    address: json['address'] as String,
    phone: json['phone'] as String,
  );
}

class ReferralGenerator {
  static Map<String, DeicInfo>? _deicData;

  static Future<Map<String, DeicInfo>> _loadDeicData() async {
    if (_deicData != null) return _deicData!;
    try {
      final jsonStr = await rootBundle.loadString('assets/data/deic_data.json');
      final Map<String, dynamic> data = json.decode(jsonStr);
      _deicData = data.map(
        (key, value) =>
            MapEntry(key, DeicInfo.fromJson(value as Map<String, dynamic>)),
      );
    } catch (_) {
      _deicData = {};
    }
    return _deicData!;
  }

  static Future<DeicInfo?> getDeicByDistrict(String districtCode) async {
    final data = await _loadDeicData();
    return data[districtCode];
  }

  static Future<File> generateReferralPDF(SessionModel session) async {
    final deic = await getDeicByDistrict(session.districtCode);
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'MozhiMuthal — Developmental Screening Referral',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 12),
            pw.Text(
              'Date: ${DateFormat('dd MMM yyyy').format(session.sessionDate)}',
            ),
            pw.Text('Anganwadi ID: ${session.anganwadiId}'),
            pw.Text('Child Age: ${session.childAgeMonths} months'),
            pw.Divider(),
            pw.Text(
              'Acoustic Biomarker Summary',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              'VTTL: ${session.vttlMs.toStringAsFixed(0)} ms ${session.vttlFlagged ? "⚠ Flagged" : "✓ Normal"}',
            ),
            pw.Text(
              'CVR Ratio: ${session.cvrRatio.toStringAsFixed(3)} ${session.cvrFlagged ? "⚠ Flagged" : "✓ Normal"}',
            ),
            if (session.pfvFlagged || session.childAgeMonths >= 36)
              pw.Text(
                'PFV Std Dev: ${session.pfvStd.toStringAsFixed(2)} ${session.pfvFlagged ? "⚠ Flagged" : "✓ Normal"}',
              ),
            pw.Divider(),
            pw.Text('This child requires further evaluation at a DEIC center.'),
            pw.SizedBox(height: 12),
            if (deic != null) ...[
              pw.Text(
                'Nearest DEIC:',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(deic.name),
              pw.Text(deic.address),
              pw.Text('Phone: ${deic.phone}'),
            ],
            pw.SizedBox(height: 24),
            pw.Text(
              'Generated by MozhiMuthal Acoustic Screening System',
              style: pw.TextStyle(
                fontSize: 9,
                color: PdfColor.fromHex('#999999'),
              ),
            ),
          ],
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/referral_${session.id}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
